version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install # Installs all required dependencies

  build:
    commands:
      - echo Building the Next.js application...
      - npm run build # Builds the Next.js app for production

artifacts:
  files:
    - '**/*'  # Include all files in the project directory, not just the .next folder
  base-directory: ./  # Base directory should be the project root, not .next

cache:
  paths:
    - node_modules/**/* # Caches node_modules to speed up subsequent builds
